// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const DEFAULT_NAV_MENUS: typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider').DEFAULT_NAV_MENUS
  const EffectScope: typeof import('vue').EffectScope
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const applyNavConfig: typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider').applyNavConfig
  const applyTheme: typeof import('D:/code/front-end/52pjhelper/src/utils/themeManager').applyTheme
  const browser: typeof import('wxt/browser').browser
  const cleanupQuickReply: typeof import('D:/code/front-end/52pjhelper/src/utils/quickReply').cleanupQuickReply
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createAvatarQuery: typeof import('D:/code/front-end/52pjhelper/src/utils/avatarQuery').createAvatarQuery
  const createContentFilter: typeof import('D:/code/front-end/52pjhelper/src/utils/contentFilter').createContentFilter
  const createDefaultTime: typeof import('D:/code/front-end/52pjhelper/src/utils/defaultTime').createDefaultTime
  const createDuplicatePostDetection: typeof import('D:/code/front-end/52pjhelper/src/utils/duplicatePostDetection').createDuplicatePostDetection
  const createFeatureManager: typeof import('D:/code/front-end/52pjhelper/src/utils/featureManager').createFeatureManager
  const createFloorHighlighter: typeof import('D:/code/front-end/52pjhelper/src/utils/floorHighlighter').createFloorHighlighter
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createMessageHelper: typeof import('D:/code/front-end/52pjhelper/src/utils/messageHelper').createMessageHelper
  const createNativeFloorDisplay: typeof import('D:/code/front-end/52pjhelper/src/utils/nativeFloorDisplay').createNativeFloorDisplay
  const createSelectAll: typeof import('D:/code/front-end/52pjhelper/src/utils/selectAll').createSelectAll
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const createStorageHelper: typeof import('D:/code/front-end/52pjhelper/src/utils/storageHelper').createStorageHelper
  const createTableSelector: typeof import('D:/code/front-end/52pjhelper/src/utils/tableSelector').createTableSelector
  const createUrlMatcher: typeof import('D:/code/front-end/52pjhelper/src/utils/urlMatcher').createUrlMatcher
  const createUserLinkQuery: typeof import('D:/code/front-end/52pjhelper/src/utils/userLinkQuery').createUserLinkQuery
  const customRef: typeof import('vue').customRef
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineComponent: typeof import('vue').defineComponent
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const disableContentFilter: typeof import('D:/code/front-end/52pjhelper/src/utils/contentFilter').disableContentFilter
  const disableRowClickToCheck: typeof import('D:/code/front-end/52pjhelper/src/utils/rowClickToCheck').disableRowClickToCheck
  const effectScope: typeof import('vue').effectScope
  const enableContentFilter: typeof import('D:/code/front-end/52pjhelper/src/utils/contentFilter').enableContentFilter
  const enableRowClickToCheck: typeof import('D:/code/front-end/52pjhelper/src/utils/rowClickToCheck').enableRowClickToCheck
  const extractUidFromHref: typeof import('D:/code/front-end/52pjhelper/src/utils/userViolationFetcher').extractUidFromHref
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const fetchUserViolation: typeof import('D:/code/front-end/52pjhelper/src/utils/userViolationFetcher').fetchUserViolation
  const getContentFilterStatus: typeof import('D:/code/front-end/52pjhelper/src/utils/contentFilter').getContentFilterStatus
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentTheme: typeof import('D:/code/front-end/52pjhelper/src/utils/themeManager').getCurrentTheme
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getRowClickToCheckStatus: typeof import('D:/code/front-end/52pjhelper/src/utils/rowClickToCheck').getRowClickToCheckStatus
  const getUserInfo: typeof import('D:/code/front-end/52pjhelper/src/utils/userInfo').getUserInfo
  const getUserInfoFromCache: typeof import('D:/code/front-end/52pjhelper/src/utils/userInfo').getUserInfoFromCache
  const h: typeof import('vue').h
  const hideMenu: typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider').hideMenu
  const initQuickReply: typeof import('D:/code/front-end/52pjhelper/src/utils/quickReply').initQuickReply
  const initTheme: typeof import('D:/code/front-end/52pjhelper/src/utils/themeManager').initTheme
  const initializeContentFilter: typeof import('D:/code/front-end/52pjhelper/src/utils/contentFilter').initializeContentFilter
  const initializeNavigationHider: typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider').initializeNavigationHider
  const initializeRowClickToCheck: typeof import('D:/code/front-end/52pjhelper/src/utils/rowClickToCheck').initializeRowClickToCheck
  const inject: typeof import('vue').inject
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const loadNavConfig: typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider').loadNavConfig
  const loadQuickReplyConfig: typeof import('D:/code/front-end/52pjhelper/src/utils/quickReply').loadQuickReplyConfig
  const markRaw: typeof import('vue').markRaw
  const messageHelper: typeof import('D:/code/front-end/52pjhelper/src/utils/messageHelper').messageHelper
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const saveNavConfig: typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider').saveNavConfig
  const saveQuickReplyConfig: typeof import('D:/code/front-end/52pjhelper/src/utils/quickReply').saveQuickReplyConfig
  const saveUserInfoToCache: typeof import('D:/code/front-end/52pjhelper/src/utils/userInfo').saveUserInfoToCache
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const showMenu: typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider').showMenu
  const storage: typeof import('wxt/utils/storage').storage
  const storageHelper: typeof import('D:/code/front-end/52pjhelper/src/utils/storageHelper').storageHelper
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const toggleContentFilter: typeof import('D:/code/front-end/52pjhelper/src/utils/contentFilter').toggleContentFilter
  const toggleMenu: typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider').toggleMenu
  const toggleRowClickToCheck: typeof import('D:/code/front-end/52pjhelper/src/utils/rowClickToCheck').toggleRowClickToCheck
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const urlMatcher: typeof import('D:/code/front-end/52pjhelper/src/utils/urlMatcher').urlMatcher
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useFeatureToggle: typeof import('D:/code/front-end/52pjhelper/src/composables/useFeatureToggle').useFeatureToggle
  const useId: typeof import('vue').useId
  const useModel: typeof import('vue').useModel
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const versionChecker: typeof import('D:/code/front-end/52pjhelper/src/utils/versionChecker').versionChecker
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const watchThemeChange: typeof import('D:/code/front-end/52pjhelper/src/utils/themeManager').watchThemeChange
  const watchUserInfo: typeof import('D:/code/front-end/52pjhelper/src/utils/userInfo').watchUserInfo
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { VueFeatureConfig, UseFeatureToggleReturn } from 'D:/code/front-end/52pjhelper/src/composables/useFeatureToggle'
  import('D:/code/front-end/52pjhelper/src/composables/useFeatureToggle')
  // @ts-ignore
  export type { IAvatarQuery } from 'D:/code/front-end/52pjhelper/src/utils/avatarQuery'
  import('D:/code/front-end/52pjhelper/src/utils/avatarQuery')
  // @ts-ignore
  export type { FilterRule, IContentFilter } from 'D:/code/front-end/52pjhelper/src/utils/contentFilter'
  import('D:/code/front-end/52pjhelper/src/utils/contentFilter')
  // @ts-ignore
  export type { IDefaultTime } from 'D:/code/front-end/52pjhelper/src/utils/defaultTime'
  import('D:/code/front-end/52pjhelper/src/utils/defaultTime')
  // @ts-ignore
  export type { IDuplicatePostDetection } from 'D:/code/front-end/52pjhelper/src/utils/duplicatePostDetection'
  import('D:/code/front-end/52pjhelper/src/utils/duplicatePostDetection')
  // @ts-ignore
  export type { FeatureConfig, IFeatureManager, CreateFeatureManagerOptions } from 'D:/code/front-end/52pjhelper/src/utils/featureManager'
  import('D:/code/front-end/52pjhelper/src/utils/featureManager')
  // @ts-ignore
  export type { IFloorHighlighter } from 'D:/code/front-end/52pjhelper/src/utils/floorHighlighter'
  import('D:/code/front-end/52pjhelper/src/utils/floorHighlighter')
  // @ts-ignore
  export type { MessageResponse, IMessageHelper } from 'D:/code/front-end/52pjhelper/src/utils/messageHelper'
  import('D:/code/front-end/52pjhelper/src/utils/messageHelper')
  // @ts-ignore
  export type { INativeFloorDisplay } from 'D:/code/front-end/52pjhelper/src/utils/nativeFloorDisplay'
  import('D:/code/front-end/52pjhelper/src/utils/nativeFloorDisplay')
  // @ts-ignore
  export type { NavMenuConfig, UserNavConfig } from 'D:/code/front-end/52pjhelper/src/utils/navigationHider'
  import('D:/code/front-end/52pjhelper/src/utils/navigationHider')
  // @ts-ignore
  export type { ISelectAll } from 'D:/code/front-end/52pjhelper/src/utils/selectAll'
  import('D:/code/front-end/52pjhelper/src/utils/selectAll')
  // @ts-ignore
  export type { IStorageHelper } from 'D:/code/front-end/52pjhelper/src/utils/storageHelper'
  import('D:/code/front-end/52pjhelper/src/utils/storageHelper')
  // @ts-ignore
  export type { ITableSelector } from 'D:/code/front-end/52pjhelper/src/utils/tableSelector'
  import('D:/code/front-end/52pjhelper/src/utils/tableSelector')
  // @ts-ignore
  export type { Theme } from 'D:/code/front-end/52pjhelper/src/utils/themeManager'
  import('D:/code/front-end/52pjhelper/src/utils/themeManager')
  // @ts-ignore
  export type { UrlMatchMode, UrlMatchRule, IUrlMatcher } from 'D:/code/front-end/52pjhelper/src/utils/urlMatcher'
  import('D:/code/front-end/52pjhelper/src/utils/urlMatcher')
  // @ts-ignore
  export type { UserInfo } from 'D:/code/front-end/52pjhelper/src/utils/userInfo'
  import('D:/code/front-end/52pjhelper/src/utils/userInfo')
  // @ts-ignore
  export type { IUserLinkQuery } from 'D:/code/front-end/52pjhelper/src/utils/userLinkQuery'
  import('D:/code/front-end/52pjhelper/src/utils/userLinkQuery')
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly ContentScriptContext: UnwrapRef<typeof import('wxt/utils/content-script-context')['ContentScriptContext']>
    readonly DEFAULT_NAV_MENUS: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider')['DEFAULT_NAV_MENUS']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly InvalidMatchPattern: UnwrapRef<typeof import('wxt/utils/match-patterns')['InvalidMatchPattern']>
    readonly MatchPattern: UnwrapRef<typeof import('wxt/utils/match-patterns')['MatchPattern']>
    readonly applyNavConfig: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider')['applyNavConfig']>
    readonly applyTheme: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/themeManager')['applyTheme']>
    readonly browser: UnwrapRef<typeof import('wxt/browser')['browser']>
    readonly cleanupQuickReply: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/quickReply')['cleanupQuickReply']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createAvatarQuery: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/avatarQuery')['createAvatarQuery']>
    readonly createContentFilter: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/contentFilter')['createContentFilter']>
    readonly createDefaultTime: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/defaultTime')['createDefaultTime']>
    readonly createDuplicatePostDetection: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/duplicatePostDetection')['createDuplicatePostDetection']>
    readonly createFeatureManager: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/featureManager')['createFeatureManager']>
    readonly createFloorHighlighter: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/floorHighlighter')['createFloorHighlighter']>
    readonly createIframeUi: UnwrapRef<typeof import('wxt/utils/content-script-ui/iframe')['createIframeUi']>
    readonly createIntegratedUi: UnwrapRef<typeof import('wxt/utils/content-script-ui/integrated')['createIntegratedUi']>
    readonly createMessageHelper: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/messageHelper')['createMessageHelper']>
    readonly createNativeFloorDisplay: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/nativeFloorDisplay')['createNativeFloorDisplay']>
    readonly createSelectAll: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/selectAll')['createSelectAll']>
    readonly createShadowRootUi: UnwrapRef<typeof import('wxt/utils/content-script-ui/shadow-root')['createShadowRootUi']>
    readonly createStorageHelper: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/storageHelper')['createStorageHelper']>
    readonly createTableSelector: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/tableSelector')['createTableSelector']>
    readonly createUrlMatcher: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/urlMatcher')['createUrlMatcher']>
    readonly createUserLinkQuery: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/userLinkQuery')['createUserLinkQuery']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAppConfig: UnwrapRef<typeof import('wxt/utils/define-app-config')['defineAppConfig']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineBackground: UnwrapRef<typeof import('wxt/utils/define-background')['defineBackground']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineContentScript: UnwrapRef<typeof import('wxt/utils/define-content-script')['defineContentScript']>
    readonly defineUnlistedScript: UnwrapRef<typeof import('wxt/utils/define-unlisted-script')['defineUnlistedScript']>
    readonly defineWxtPlugin: UnwrapRef<typeof import('wxt/utils/define-wxt-plugin')['defineWxtPlugin']>
    readonly disableContentFilter: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/contentFilter')['disableContentFilter']>
    readonly disableRowClickToCheck: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/rowClickToCheck')['disableRowClickToCheck']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly enableContentFilter: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/contentFilter')['enableContentFilter']>
    readonly enableRowClickToCheck: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/rowClickToCheck')['enableRowClickToCheck']>
    readonly extractUidFromHref: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/userViolationFetcher')['extractUidFromHref']>
    readonly fakeBrowser: UnwrapRef<typeof import('wxt/testing')['fakeBrowser']>
    readonly fetchUserViolation: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/userViolationFetcher')['fetchUserViolation']>
    readonly getContentFilterStatus: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/contentFilter')['getContentFilterStatus']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentTheme: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/themeManager')['getCurrentTheme']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getRowClickToCheckStatus: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/rowClickToCheck')['getRowClickToCheckStatus']>
    readonly getUserInfo: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/userInfo')['getUserInfo']>
    readonly getUserInfoFromCache: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/userInfo')['getUserInfoFromCache']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly hideMenu: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider')['hideMenu']>
    readonly initQuickReply: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/quickReply')['initQuickReply']>
    readonly initTheme: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/themeManager')['initTheme']>
    readonly initializeContentFilter: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/contentFilter')['initializeContentFilter']>
    readonly initializeNavigationHider: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider')['initializeNavigationHider']>
    readonly initializeRowClickToCheck: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/rowClickToCheck')['initializeRowClickToCheck']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly injectScript: UnwrapRef<typeof import('wxt/utils/inject-script')['injectScript']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly loadNavConfig: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider')['loadNavConfig']>
    readonly loadQuickReplyConfig: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/quickReply')['loadQuickReplyConfig']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly messageHelper: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/messageHelper')['messageHelper']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly saveNavConfig: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider')['saveNavConfig']>
    readonly saveQuickReplyConfig: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/quickReply')['saveQuickReplyConfig']>
    readonly saveUserInfoToCache: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/userInfo')['saveUserInfoToCache']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly showMenu: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider')['showMenu']>
    readonly storage: UnwrapRef<typeof import('wxt/utils/storage')['storage']>
    readonly storageHelper: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/storageHelper')['storageHelper']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly toggleContentFilter: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/contentFilter')['toggleContentFilter']>
    readonly toggleMenu: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/navigationHider')['toggleMenu']>
    readonly toggleRowClickToCheck: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/rowClickToCheck')['toggleRowClickToCheck']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly urlMatcher: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/urlMatcher')['urlMatcher']>
    readonly useAppConfig: UnwrapRef<typeof import('wxt/utils/app-config')['useAppConfig']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useFeatureToggle: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/composables/useFeatureToggle')['useFeatureToggle']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly versionChecker: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/versionChecker')['versionChecker']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly watchThemeChange: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/themeManager')['watchThemeChange']>
    readonly watchUserInfo: UnwrapRef<typeof import('D:/code/front-end/52pjhelper/src/utils/userInfo')['watchUserInfo']>
  }
}
