// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { getAppConfig, useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onErrorCaptured, onDeactivated, onMounted, onServerPrefetch, onUnmounted, onUpdated, useAttrs, useSlots, computed, customRef, isReadonly, isRef, isShallow, isProxy, isReactive, markRaw, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, triggerRef, toRaw, toRef, toRefs, toValue, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, defineComponent, defineAsyncComponent, getCurrentInstance, h, inject, nextTick, provide, useCssModule, createApp, effectScope, EffectScope, getCurrentScope, onScopeDispose, Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef, onRenderTracked, onRenderTriggered, resolveComponent, useCssVars, useModel, getCurrentWatcher, onWatcherCleanup, useId, useTemplateRef } from 'vue';
  export { fakeBrowser } from 'wxt/testing';
  export { useFeatureToggle, VueFeatureConfig, UseFeatureToggleReturn } from '../src/composables/useFeatureToggle';
  export { createAvatarQuery, IAvatarQuery } from '../src/utils/avatarQuery';
  export { initializeContentFilter, enableContentFilter, disableContentFilter, toggleContentFilter, getContentFilterStatus, createContentFilter, FilterRule, IContentFilter } from '../src/utils/contentFilter';
  export { createDefaultTime, IDefaultTime } from '../src/utils/defaultTime';
  export { createDuplicatePostDetection, IDuplicatePostDetection } from '../src/utils/duplicatePostDetection';
  export { createFeatureManager, FeatureConfig, IFeatureManager, CreateFeatureManagerOptions } from '../src/utils/featureManager';
  export { createFloorHighlighter, IFloorHighlighter } from '../src/utils/floorHighlighter';
  export { createMessageHelper, messageHelper, MessageResponse, IMessageHelper } from '../src/utils/messageHelper';
  export { createNativeFloorDisplay, INativeFloorDisplay } from '../src/utils/nativeFloorDisplay';
  export { DEFAULT_NAV_MENUS, saveNavConfig, loadNavConfig, hideMenu, showMenu, applyNavConfig, toggleMenu, initializeNavigationHider, NavMenuConfig, UserNavConfig } from '../src/utils/navigationHider';
  export { loadQuickReplyConfig, saveQuickReplyConfig, initQuickReply, cleanupQuickReply } from '../src/utils/quickReply';
  export { initializeRowClickToCheck, enableRowClickToCheck, disableRowClickToCheck, toggleRowClickToCheck, getRowClickToCheckStatus } from '../src/utils/rowClickToCheck';
  export { createSelectAll, ISelectAll } from '../src/utils/selectAll';
  export { createStorageHelper, storageHelper, IStorageHelper } from '../src/utils/storageHelper';
  export { createTableSelector, ITableSelector } from '../src/utils/tableSelector';
  export { getCurrentTheme, applyTheme, watchThemeChange, initTheme, Theme } from '../src/utils/themeManager';
  export { createUrlMatcher, urlMatcher, UrlMatchMode, UrlMatchRule, IUrlMatcher } from '../src/utils/urlMatcher';
  export { saveUserInfoToCache, getUserInfoFromCache, getUserInfo, watchUserInfo, UserInfo } from '../src/utils/userInfo';
  export { createUserLinkQuery, IUserLinkQuery } from '../src/utils/userLinkQuery';
  export { fetchUserViolation, extractUidFromHref } from '../src/utils/userViolationFetcher';
  export { versionChecker } from '../src/utils/versionChecker';
}
